# MCPJungle Docker Compose configuration
# Self-hosted MCP Gateway and Registry for HomeLab

services:
  db:
    image: postgres:17-alpine
    container_name: mcpjungle-db
    environment:
      POSTGRES_USER: mcpjungle
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mcpjungle}
      POSTGRES_DB: mcpjungle
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcpjungle"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - mcp

  mcpjungle:
    image: mcpjungle/mcpjungle:${MCPJUNGLE_IMAGE_TAG:-latest-stdio}
    container_name: mcpjungle
    environment:
      DATABASE_URL: postgres://mcpjungle:${POSTGRES_PASSWORD:-mcpjungle}@db:5432/mcpjungle
      SERVER_MODE: ${SERVER_MODE:-development}
      OTEL_ENABLED: ${OTEL_ENABLED:-false}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES:-}
    ports:
      - "${HOST_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/mcp/workspace:/host:rw
      - uploads:/uploads
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mcp

volumes:
  db_data:
  uploads:

networks:
  mcp:
    driver: bridge
